package com.jianma.tagsystem.module;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "tag_example")
public class Tag implements java.io.Serializable {

	private Integer id;
	private TagCategory tagCategory;
	private String tagName;
	private Date createTime;
	private Set<ArticleTag> articleTags = new HashSet<ArticleTag>(0);

	public Tag() {
	}

	public Tag(TagCategory tagCategory, String tagName, Date createTime) {
		this.tagCategory = tagCategory;
		this.tagName = tagName;
		this.createTime = createTime;
	}

	public Tag(TagCategory tagCategory, String tagName, Date createTime, Set<ArticleTag> articleTags) {
		this.tagCategory = tagCategory;
		this.tagName = tagName;
		this.createTime = createTime;
		this.articleTags = articleTags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tag_category_id", nullable = false)
	public TagCategory getTagCategory() {
		return this.tagCategory;
	}

	public void setTagCategory(TagCategory tagCategory) {
		this.tagCategory = tagCategory;
	}

	@Column(name = "tag_name", nullable = false, length = 20)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<ArticleTag> getArticleTags() {
		return this.articleTags;
	}

	public void setArticleTags(Set<ArticleTag> articleTags) {
		this.articleTags = articleTags;
	}

}
