package com.jianma.tagsystem.module;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TagCategory generated by hbm2java
 */
@Entity
@Table(name = "tag_category", catalog = "tag_example")
public class TagCategory implements java.io.Serializable {

	private Integer id;
	private String categoryName;
	private Date createTime;
	private Set<Tag> tags = new HashSet<Tag>(0);

	public TagCategory() {
	}

	public TagCategory(String categoryName, Date createTime) {
		this.categoryName = categoryName;
		this.createTime = createTime;
	}

	public TagCategory(String categoryName, Date createTime, Set<Tag> tags) {
		this.categoryName = categoryName;
		this.createTime = createTime;
		this.tags = tags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "category_name", nullable = false, length = 20)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tagCategory")
	public Set<Tag> getTags() {
		return this.tags;
	}

	public void setTags(Set<Tag> tags) {
		this.tags = tags;
	}

}
